import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    bpm: 120,
    beat: [
      {
        instrument: "0",
        data: [
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.75" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.55" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.7" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.8" },
          { on: false, velocity: 1 },
        ],
      },
      {
        instrument: "2",
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
        ],
      },
      {
        instrument: "1",
        data: [
          { on: false, velocity: 1 },
          { on: true, velocity: "0.3" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.35" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.3" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.45" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.15" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.4" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.3" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.25" },
        ],
      },
      {
        instrument: "3",
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: "0.65" },
          { on: false, velocity: "0.75" },
          { on: true, velocity: "0.45" },
          { on: true, velocity: "0" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.65" },
        ],
      },
      {
        instrument: "4",
        data: [
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
        ],
      },
      {
        instrument: "5",
        data: [
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.65" },
          { on: true, velocity: "0.5" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.4" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.2" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.35" },
          { on: true, velocity: "0.55" },
        ],
      },
      {
        instrument: "6",
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.75" },
          { on: true, velocity: "0.4" },
        ],
      },
    ],
  },
  {
    bpm: 120,
    beat: [
      {
        instrument: 1,
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: "0" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.55" },
          { on: true, velocity: "0.15" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.7" },
          { on: true, velocity: "0.45" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "1" },
          { on: true, velocity: "0.7" },
          { on: true, velocity: "0.4" },
        ],
      },
      {
        instrument: 3,
        data: [
          { on: true, velocity: "0.05" },
          { on: true, velocity: "0.05" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "1" },
          { on: true, velocity: "0.2" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.35" },
          { on: true, velocity: "0.15" },
          { on: true, velocity: "0.05" },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.95" },
          { on: true, velocity: "0.3" },
          { on: true, velocity: "0.2" },
          { on: true, velocity: "0.65" },
        ],
      },
      {
        instrument: 6,
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.65" },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.55" },
        ],
      },
    ],
  },
  {
    bpm: 120,
    beat: [
      {
        instrument: 1,
        data: [
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
        ],
      },
      {
        instrument: 3,
        data: [
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
        ],
      },
      {
        instrument: 6,
        data: [
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: true, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
          { on: false, velocity: 1.0 },
        ],
      },
    ],
  },
  {
    bpm: 120,
    beat: [
      {
        instrument: "2",
        data: [
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.75" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.55" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.7" },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.8" },
          { on: false, velocity: 1 },
        ],
      },
      {
        instrument: "1",
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
        ],
      },
      {
        instrument: "4",
        data: [
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
        ],
      },
      {
        instrument: "6",
        data: [
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: "0.65" },
          { on: false, velocity: "0.75" },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
          { on: false, velocity: 1 },
          { on: false, velocity: 1 },
          { on: true, velocity: 1 },
        ],
      },
    ],
  },
];

const defaultChannel = {
  instrument: 3,
  data: [
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
    { on: false, velocity: 1.0 },
  ],
};

export const beatSlice = createSlice({
  name: "beat",
  initialState,
  reducers: {
    toggleBeat: (state, action) => {
      const beat = action.payload.beatIndex;
      const channel = action.payload.channelIndex;
      const note = action.payload.noteIndex;
      state[beat].beat[channel].data[note].on =
        !state[beat].beat[channel].data[note].on;
    },
    setVelocity: (state, action) => {
      const beat = action.payload.beatIndex;
      const channel = action.payload.channelIndex;
      const note = action.payload.noteIndex;
      state[beat].beat[channel].data[note].velocity = action.payload.velocity;
    },
    setBpm: (state, action) => {
      const beat = action.payload.beatIndex;
      state[beat].bpm = action.payload.bpm;
    },
    setInstrument: (state, action) => {
      const beat = action.payload.beatIndex;
      const channel = action.payload.channelIndex;
      state[beat].beat[channel].instrument = action.payload.instrument;
    },
    addChannel: (state, action) => {
      const beat = action.payload.beatIndex;
      state[beat].beat.push(defaultChannel);
    },
    removeChannel: (state, action) => {
      const beat = action.payload.beatIndex;
      const channel = action.payload.channelIndex;
      state[beat].beat.splice(channel, 1);
    },
  },
});

export const {
  toggleBeat,
  setVelocity,
  setBpm,
  setInstrument,
  addChannel,
  removeChannel,
} = beatSlice.actions;
export default beatSlice.reducer;
