

const tracks = [
  [[{on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}],
  [{on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}],
  [{on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}]],

  [[{on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}, {on: true, velocity: 1.0}, {on: true, velocity: .5}],
  [{on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}],
  [{on: true, velocity: 1.0}, {on: true, velocity: .3}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}]],

  [[{on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}],
  [{on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}],
  [{on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0}, {on: true, velocity: 1.0}, {on: false, velocity: 1.0},{on: false, velocity: 1.0} , {on: false, velocity: 1.0}, {on: false, velocity: 1.0}, {on: false, velocity: 1.0}]]

];

export default tracks;